apiVersion: v1
kind: Service
metadata:
  name: drone-app-service
spec:
  type: NodePort
  selector:
    app: drone-app
  ports:
    - protocol: TCP
      port: 8060
      targetPort: 8060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-app-deployment
  labels:
    app: drone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-app
  template:
    metadata:
      labels:
        app: drone-app
    spec:
      containers:
        - name: drone-app
          image: evandroborzi/drone-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8060